name: Checkout and Sync Repos
description: Download repo tool, init manifest, apply owner/ref overrides via local manifest, and sync projects.

inputs:
  ai-ml-sdk-model-converter_owner:
    description: GitHub owner/org for ai-ml-sdk-model-converter
    required: false
    default: arm
  ai-ml-sdk-model-converter_revision:
    description: Revision (ref) for ai-ml-sdk-model-converter
    required: false
    default: main

  ai-ml-sdk-scenario-runner_owner:
    description: GitHub owner/org for ai-ml-sdk-scenario-runner
    required: false
    default: arm
  ai-ml-sdk-scenario-runner_revision:
    description: Revision (ref) for ai-ml-sdk-scenario-runner
    required: false
    default: main

  ai-ml-sdk-vgf-library_owner:
    description: GitHub owner/org for ai-ml-sdk-vgf-library
    required: false
    default: arm
  ai-ml-sdk-vgf-library_revision:
    description: Revision (ref) for ai-ml-sdk-vgf-library
    required: false
    default: main

  ai-ml-emulation-layer-for-vulkan_owner:
    description: GitHub owner/org for ai-ml-emulation-layer-for-vulkan
    required: false
    default: arm
  ai-ml-emulation-layer-for-vulkan_revision:
    description: Revision (ref) for ai-ml-emulation-layer-for-vulkan
    required: false
    default: main

  ai-ml-sdk-for-vulkan_owner:
    description: GitHub owner/org for ai-ml-sdk-for-vulkan
    required: false
    default: arm
  ai-ml-sdk-for-vulkan_revision:
    description: Revision (ref) for ai-ml-sdk-for-vulkan
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Enable long paths and download repo (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" -Name "LongPathsEnabled" -Value 1
        git config --global core.longpaths true
        $repoDir = "$HOME\\.bin\\git-repo"
        $repoBin = "$repoDir\\repo"
        New-Item -ItemType Directory -Force -Path $repoDir | Out-Null
        curl.exe -L "https://storage.googleapis.com/git-repo-downloads/repo" -o $repoBin

    - name: Download repo tool (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p "$HOME/.bin/git-repo"
        curl -L https://storage.googleapis.com/git-repo-downloads/repo -o "$HOME/.bin/git-repo/repo"
        chmod +x "$HOME/.bin/git-repo/repo"

    - name: repo init (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python "$HOME\\.bin\\git-repo\\repo" init -u https://github.com/arm/ai-ml-sdk-manifest.git --depth=1

    - name: repo init (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        python "$HOME/.bin/git-repo/repo" init -u https://github.com/arm/ai-ml-sdk-manifest.git --depth=1

    - name: repo sync (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python "$HOME\\.bin\\git-repo\\repo" sync

    # Conditional overrides: Only checkout if owner/ref differs from defaults
    - name: Override ai-ml-sdk-for-vulkan (if changed)
      if: ${{ inputs.ai-ml-sdk-for-vulkan_owner != 'arm' || inputs.ai-ml-sdk-for-vulkan_revision != 'main' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ai-ml-sdk-for-vulkan_owner }}/ai-ml-sdk-for-vulkan
        ref: ${{ inputs.ai-ml-sdk-for-vulkan_revision }}
        path: .
    - name: Override ai-ml-sdk-model-converter (if changed)
      if: ${{ inputs.ai-ml-sdk-model-converter_owner != 'arm' || inputs.ai-ml-sdk-model-converter_revision != 'main' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ai-ml-sdk-model-converter_owner }}/ai-ml-sdk-model-converter
        ref: ${{ inputs.ai-ml-sdk-model-converter_revision }}
        path: sw/model-converter
    - name: Override ai-ml-sdk-scenario-runner (if changed)
      if: ${{ inputs.ai-ml-sdk-scenario-runner_owner != 'arm' || inputs.ai-ml-sdk-scenario-runner_revision != 'main' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ai-ml-sdk-scenario-runner_owner }}/ai-ml-sdk-scenario-runner
        ref: ${{ inputs.ai-ml-sdk-scenario-runner_revision }}
        path: sw/scenario-runner
    - name: Override ai-ml-sdk-vgf-library (if changed)
      if: ${{ inputs.ai-ml-sdk-vgf-library_owner != 'arm' || inputs.ai-ml-sdk-vgf-library_revision != 'main' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ai-ml-sdk-vgf-library_owner }}/ai-ml-sdk-vgf-library
        ref: ${{ inputs.ai-ml-sdk-vgf-library_revision }}
        path: sw/vgf-lib
    - name: Override ai-ml-emulation-layer-for-vulkan (if changed)
      if: ${{ inputs.ai-ml-emulation-layer-for-vulkan_owner != 'arm' || inputs.ai-ml-emulation-layer-for-vulkan_revision != 'main' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ai-ml-emulation-layer-for-vulkan_owner }}/ai-ml-emulation-layer-for-vulkan
        ref: ${{ inputs.ai-ml-emulation-layer-for-vulkan_revision }}
        path: sw/emulation-layer

    - name: repo sync (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        python "$HOME/.bin/git-repo/repo" sync

